### ISSUE TITLE
Feast

### ISSUE THREAD

**Issue by jvsant0s** [odukjung/Auto-Food-Upgrade#1]
Can u do something to mod dont use food when some low iq player popping a fucking feast near party, the messages spam on screen kinda annoying

**Comment by odukjung** [comment]
what do u mean ?
fucking feast is Friendly Feast or Federation Supply: Feast ?
what your food to use at that time?

**Comment by jvsant0s** [comment]
Normal feast, if someone pop this the mod keep trying to use power food but we can use power food with feast

**Comment by jvsant0s** [comment]
https://prnt.sc/1vbpqh4 this one

**Comment by odukjung** [comment]
fix
